### ISSUE TITLE
Recommended way of updating competition 

### ISSUE THREAD

**Issue by dookgit** [pwnbus/scoring_engine#709]
Heya

So i've got ScoringEngine all running Ok in Docker, and am adding services to be monitored to competion.yaml.  But just wanted to confirm if i'm doing it the preferred way.

Current process

1. docker-compose -f docker-compose.yml stop
2. copy my updated competition.yaml file into scoringengine/bin directory
3. make rebuild-new

Is that right?   Just wanna make sure i'm not going over the top, as i'm making very incremental changes as i go in competition.yaml, then repeating the process for new services.

Cheers

**Comment by RustyBower** [comment]
I can check when I'm at my laptop tomorrow, but that should be fine. Ideally you'd only need to rebuild the engine since all the checks are stored there, but I'll confirm that.

**Comment by RustyBower** [comment]
Closing this out for now, let me know if you have any further questions and I can answer
