### ISSUE TITLE
Feature Request - Localize Scripts and CSS

### ISSUE THREAD

**Issue by mubix** [pwnbus/scoring_engine#732]
Currently there are a few javascript and CSS files that get loaded from the Internet to be able to show the scoreboard. It would be nice to not have to figure out what these are ahead of time and have everything local.

**Comment by RustyBower** [comment]
Yeah... I missed vendoring a few of these before the competition. I'll get those squared away today.

**Comment by RustyBower** [comment]
Fixed in https://github.com/scoringengine/scoringengine/commit/b9bf23d63df0fc28d2fbc269d29dff6e7c66202f
