### ISSUE TITLE
Fix Dependencies

### ISSUE THREAD

**Issue by cryptnetworks** [pwnbus/scoring_engine#843]
Werkzueg and Flask need to be on versions 2.2.2 to ensure they are compatatible.

<img width="979" alt="image" src="https://github.com/scoringengine/scoringengine/assets/85764894/c8410166-8f35-4011-bc72-886d0c812e21">

**Comment by mkhawam** [comment]
Was there an update on this because I've been having the same issue.

**Comment by RustyBower** [comment]
Feel free to open a PR for this, otherwise I will hopefully get to it this weekend.

**Comment by mkhawam** [comment]
I fixed it by modifying the setup.py to choose Werkzeug 2.3.6 instead. had no issues deploying the container after that
```txt
- # 'Werkzeug==0.16.1',
+ 'Werkzeug==2.3.6',
```

**Comment by RustyBower** [comment]
should be fixed as part of https://github.com/scoringengine/scoringengine/pull/852
